cors:
  originPatterns: "http://localhost:8080,https://erudio.com.br,http://localhost:3000"
security:
  jwt:
    token:
      secret-key: 53cr27
      expired-length: 3600000
      refresh-expired-length: 18000000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC-3
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  springdoc:
    pathsToMatch: /**
    swagger-ui:
      use-root-path: true

